version: '3'
services:
  database:
    image: postgres:alpine
    container_name: "home_server_database"
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - home_server_db:/var/lib/postgresql/data

  user_service:
    image: darren25/user_service:latest
    container_name: "home_server_user_service"
    ports:
      - "3000:3000"
    depends_on:
      - database

  beer_service:
    image: darren25/beer_service:latest
    container_name: "home_server_beer_service"
    ports:
      - "3001:3001"
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - beer_service
      - user_service


volumes:
  home_server_db:
    driver: local
