version: '3'
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      -"5432:5432"
    volumes:
      -home_server_db:/var/lib/postgresql/data

  user_service:
    image: user_service/latest
    build: ./user_service
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  home_server_db:
    driver: local
