version: '3'
services:
  database:
    image: postgres:alpine
    container_name: "home_server_database"
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - home_server_db:/var/lib/postgresql/data

  member_portal:
    image: darren25/member_portal:latest
    container_name: "home_server_member_portal"
    ports:
      - "3002:3002"
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - member_portal


volumes:
  home_server_db:
    driver: local