version: '3'
services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - home_server_db:/var/lib/postgresql/data

  user_service:
    image: darren25/user_service:latest
    ports:
      - "3000:3000"
    depends_on:
      - database

  beer_service:
    image: darren25/beer_service:latest
    ports:
      - "3001:3001"
    depends_on:
      - database


volumes:
  home_server_db:
    driver: local
