name: "Build Test and Deploy to Production"

on:
  push:
    branches:
      - main

env:
  SQLX_OFFLINE: true

jobs:
  member_portal_build:
    uses: ./.github/workflows/build-publish.yml
    with:
      service-name: "member_portal"
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [member_portal_build]

    uses: ./.github/workflows/deploy.yml

    with:
      DROPLET_IP: ${{ vars.DROPLET_IP }}
      DROPLET_USER: ${{ vars.DROPLET_USER }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
    secrets:
      DROPLET_SSH_PRIVATE_KEY_BASE64: ${{ secrets.DROPLET_SSH_PRIVATE_KEY_BASE64 }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
